// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5EuDYH5GRAlB7Gtc92dvbOCDVUehk-lQ',
    appId: '1:852447269000:web:3937931e8033f4d8d8cf3d',
    messagingSenderId: '852447269000',
    projectId: 'ia-recipe-project',
    authDomain: 'ia-recipe-project.firebaseapp.com',
    storageBucket: 'ia-recipe-project.firebasestorage.app',
    measurementId: 'G-F5565W0FFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCymru2G1xBKQgMU81IPsJb2TUkuk_nYTs',
    appId: '1:852447269000:android:652b5d907fea2fe1d8cf3d',
    messagingSenderId: '852447269000',
    projectId: 'ia-recipe-project',
    storageBucket: 'ia-recipe-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcGmIPt0EoY8CZvJTpKY2sVMs171pYPkk',
    appId: '1:852447269000:ios:43cef6156280081dd8cf3d',
    messagingSenderId: '852447269000',
    projectId: 'ia-recipe-project',
    storageBucket: 'ia-recipe-project.firebasestorage.app',
    iosBundleId: 'com.recipeai.recipeai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcGmIPt0EoY8CZvJTpKY2sVMs171pYPkk',
    appId: '1:852447269000:ios:43cef6156280081dd8cf3d',
    messagingSenderId: '852447269000',
    projectId: 'ia-recipe-project',
    storageBucket: 'ia-recipe-project.firebasestorage.app',
    iosBundleId: 'com.recipeai.recipeai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5EuDYH5GRAlB7Gtc92dvbOCDVUehk-lQ',
    appId: '1:852447269000:web:e985ca8a6222a806d8cf3d',
    messagingSenderId: '852447269000',
    projectId: 'ia-recipe-project',
    authDomain: 'ia-recipe-project.firebaseapp.com',
    storageBucket: 'ia-recipe-project.firebasestorage.app',
    measurementId: 'G-ZR2Q10D56L',
  );
}
